from typing import Protocol


class EmbeddingProvider(Protocol):
    def model_id(self) -> str: ...
    def dimension(self) -> int: ...
    def embed_texts(self, texts: list[str]) -> list[list[float]]: ...